name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GITHUB_USER: nth-commit
  GITHUB_TOKEN: ${{ secrets.MY_GET_API_KEY }}
  GITHUB_FEED: https://www.myget.org/F/galaxy-check/api/v2/package
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  PACKABLE_PROJECTS: GalaxyCheck GalaxyCheck.Xunit NebulaCheck

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  pack:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Make NebulaCheck
        run: |
          find ./src/GalaxyCheck -type d -print0 | while read -d $'\0' currFilename; do
            newFilename=$(echo "$currFilename" | sed "s/GalaxyCheck/NebulaCheck/g")
            mkdir $newFilename
          done

          find ./src/GalaxyCheck -type f -print0 | while read -d $'\0' currFilename; do
            newFilename=$(echo $currFilename | sed "s/GalaxyCheck/NebulaCheck/g")
            cat $currFilename | sed "s/GalaxyCheck/NebulaCheck/g" > $newFilename
          done

          sed -i -e "s|https://github.com/nth-commit/NebulaCheck|https://github.com/nth-commit/GalaxyCheck|g" ./src/NebulaCheck/NebulaCheck.csproj
      - name: Restore
        run: |
          for project in $PACKABLE_PROJECTS; do
            dotnet restore src/$project/$project.csproj
          done
      - name: Build
        run: |
          for project in $PACKABLE_PROJECTS; do
            dotnet build --no-restore src/$project/$project.csproj
          done
      - name: Pack
        run: |
          for project in $PACKABLE_PROJECTS; do
            dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=0.0.0-$GITHUB_RUN_ID src/$project/$project.csproj
          done
      - name: Collect
        run: |
          mkdir ./nupkg
          for f in $(find . -name '*.nupkg'); do
            mv $f ./nupkg
          done
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./nupkg

  prerelease:
    needs: pack
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: nupkg
      - name: Push
        run: |
          for f in ./nupkg/*.nupkg
          do
            dotnet nuget push $f --api-key $GITHUB_TOKEN --source $GITHUB_FEED
          done
